import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { z } from 'zod';
import * as fs from 'fs';
import * as path from 'path';
import * as yaml from 'js-yaml';

// Define the HTTP methods enum
const HttpMethod = z.enum(['GET', 'POST', 'PUT', 'DELETE', 'PATCH', 'OPTIONS', 'HEAD']);
type HttpMethodType = z.infer<typeof HttpMethod>;

/**
 * Configure add_route tool for creating FastAPI route stubs
 */
export function addRouteTool(server: McpServer, repoRoot: string): void {
  server.tool(
    'add_route',
    {
      path: z.string().min(1),
      method: HttpMethod,
      handler_name: z.string().min(1)
    },
    async ({ path: routePath, method, handler_name }) => {
      try {
        // Normalize the route path
        const normalizedPath = routePath.startsWith('/') ? routePath : `/${routePath}`;
        
        // 1. Add route to vibe.yaml OpenAPI specification
        const vibeYamlPath = path.join(repoRoot, 'vibe.yaml');
        let spec: any;
        
        if (fs.existsSync(vibeYamlPath)) {
          spec = yaml.load(fs.readFileSync(vibeYamlPath, 'utf8')) as any;
        } else {
          // Create basic spec if it doesn't exist
          spec = {
            openapi: '3.0.0',
            info: {
              title: 'API Specification',
              version: '1.0.0',
              description: 'API specification generated by Carrot MCP'
            },
            paths: {}
          };
        }

        // Ensure paths object exists
        if (!spec.paths) {
          spec.paths = {};
        }

        // Ensure the path exists in the spec
        if (!spec.paths[normalizedPath]) {
          spec.paths[normalizedPath] = {};
        }

        // Add the method to the path
        const methodLower = method.toLowerCase();
        spec.paths[normalizedPath][methodLower] = {
          summary: `${method} ${normalizedPath}`,
          description: `Handler: ${handler_name}`,
          operationId: handler_name,
          responses: {
            '200': {
              description: 'Successful response',
              content: {
                'application/json': {
                  schema: {
                    type: 'object',
                    properties: {
                      message: { type: 'string' }
                    }
                  }
                }
              }
            },
            '400': { $ref: '#/components/responses/BadRequest' },
            '404': { $ref: '#/components/responses/NotFound' }
          }
        };

        // Add request body for POST/PUT/PATCH methods
        if (['POST', 'PUT', 'PATCH'].includes(method)) {
          spec.paths[normalizedPath][methodLower].requestBody = {
            description: 'Request payload',
            required: true,
            content: {
              'application/json': {
                schema: {
                  type: 'object',
                  properties: {
                    // Add basic properties - can be customized later
                  }
                }
              }
            }
          };
        }

        // Ensure components section exists with common responses
        if (!spec.components) {
          spec.components = {};
        }
        if (!spec.components.responses) {
          spec.components.responses = {};
        }

        // Add common response components if they don't exist
        if (!spec.components.responses.BadRequest) {
          spec.components.responses.BadRequest = {
            description: 'The request was invalid',
            content: {
              'application/json': {
                schema: {
                  type: 'object',
                  properties: {
                    error: { type: 'string', example: 'Invalid request' },
                    status: { type: 'integer', example: 400 }
                  }
                }
              }
            }
          };
        }
        
        if (!spec.components.responses.NotFound) {
          spec.components.responses.NotFound = {
            description: 'The requested resource was not found',
            content: {
              'application/json': {
                schema: {
                  type: 'object',
                  properties: {
                    error: { type: 'string', example: 'Resource not found' },
                    status: { type: 'integer', example: 404 }
                  }
                }
              }
            }
          };
        }

        // Write updated spec back to vibe.yaml
        fs.writeFileSync(vibeYamlPath, yaml.dump(spec, { indent: 2 }));
        
        // 2. Create detailed route specification file
        const specsApiDir = path.join(repoRoot, 'specs', 'api');
        if (!fs.existsSync(specsApiDir)) {
          fs.mkdirSync(specsApiDir, { recursive: true });
        }

        // Create a spec file for this route
        const routeSpecFileName = `${handler_name.replace(/([a-z])([A-Z])/g, '$1_$2').toLowerCase()}.json`;
        const routeSpecPath = path.join(specsApiDir, routeSpecFileName);

        const routeSpec = {
          route: {
            path: normalizedPath,
            method: method,
            handler: handler_name,
            summary: `${method} ${normalizedPath}`,
            description: `Detailed specification for ${handler_name}`,
            created: new Date().toISOString()
          },
          implementation: {
            status: 'specification',
            requirements: [
              'Implement request validation',
              'Add proper error handling',
              'Include logging',
              'Add unit tests'
            ],
            dependencies: [],
            notes: 'Generated by Carrot AI PM add_route tool'
          },
          testing: {
            testCases: [
              {
                name: 'successful_request',
                description: 'Test successful request handling',
                input: {},
                expectedStatus: 200
              },
              {
                name: 'invalid_request',
                description: 'Test invalid request handling',
                input: {},
                expectedStatus: 400
              }
            ]
          }
        };

        fs.writeFileSync(routeSpecPath, JSON.stringify(routeSpec, null, 2));
        
        return {
          content: [{ 
            type: 'text', 
            text: `Successfully added ${method} route specification for ${normalizedPath}\n\n` +
                  `Updated:\n` +
                  `- vibe.yaml: Added ${methodLower} operation to ${normalizedPath}\n` +
                  `- ${path.relative(repoRoot, routeSpecPath)}: Created detailed route specification\n\n` +
                  `The route specification is ready for implementation. Use the spec file to guide development.`
          }]
        };
      } catch (error) {
        return {
          content: [{ 
            type: 'text', 
            text: `Error adding route specification: ${error instanceof Error ? error.message : String(error)}` 
          }],
          isError: true
        };
      }
    }
  );
} 