import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { z } from 'zod';
import * as fs from 'fs';
import * as path from 'path';
import * as yaml from 'js-yaml';

/**
 * Configure grow_spec tool for adding entries to the spec repository
 */
export function growSpecTool(server: McpServer, repoRoot: string): void {
  console.log('Initializing grow_spec tool with repo root:', repoRoot);
  
  server.tool(
    'grow_spec',
    {
      endpoint: z.string().min(1).describe('The API endpoint path to generate a specification for'),
      summary: z.string().min(1).describe('A brief summary of the endpoint\'s purpose'),
      projectDir: z.string().optional().describe('Target project directory where specs should be generated. If not provided, will use current directory.')
    },
    async ({ endpoint, summary, projectDir }: { endpoint: string; summary: string; projectDir?: string }) => {
      try {
        console.log(`grow_spec tool called with endpoint: ${endpoint}, summary: ${summary}, projectDir: ${projectDir}`);
        
        // Use the repository root as a stable base directory so that subsequent
        // calls do not depend on whatever the current working directory might
        // have been changed to elsewhere in the application lifecycle.
        const baseDir = repoRoot;
        console.log('Base directory:', baseDir);
        
        // Resolve target directory with better path handling
        const targetDir = projectDir ? 
          (path.isAbsolute(projectDir) ? 
            // If absolute path, validate it's a user directory (not system)
            (projectDir.startsWith('/Users') || projectDir.startsWith('/home') ? projectDir : path.join(baseDir, projectDir)) :
            // If relative path, resolve from the repo root
            path.resolve(baseDir, projectDir)
          ) : 
          baseDir;
        
        console.log(`Using target directory: ${targetDir}`);

        // Enhanced safety checks for system directories
        if (targetDir === '/' || 
            targetDir.startsWith('/usr') || 
            targetDir.startsWith('/etc') || 
            targetDir.startsWith('/var') || 
            targetDir.startsWith('/tmp')) {
          throw new Error(`Cannot write to system directory: ${targetDir}`);
        }

        // Ensure target directory exists with logging
        if (!fs.existsSync(targetDir)) {
          console.log(`Creating target directory ${targetDir}...`);
          try {
            fs.mkdirSync(targetDir, { recursive: true });
          } catch (err: any) {
            console.error(`Failed to create directory ${targetDir}:`, err);
            throw new Error(`Failed to create directory ${targetDir}: ${err.message}`);
          }
        }
        
        // vibe.yaml is pinned to the repo root – never inside projectDir.
        const vibeYamlPath = path.join(repoRoot, 'vibe.yaml');
        
        // Create or read vibe.yaml with proper error handling
        let existingYaml;
        if (fs.existsSync(vibeYamlPath)) {
          try {
            existingYaml = yaml.load(fs.readFileSync(vibeYamlPath, 'utf8')) as any;
          } catch (err: any) {
            console.error(`Error reading ${vibeYamlPath}:`, err);
            throw new Error(`Failed to read ${vibeYamlPath}: ${err.message}`);
          }
        } else {
          // Create initial OpenAPI spec
          existingYaml = {
            openapi: '3.0.0',
            info: {
              title: 'API Specification',
              version: '1.0.0',
              description: 'API specification generated by Carrot MCP'
            },
            paths: {}
          };
        }
        
        // Ensure paths object exists
        if (!existingYaml.paths) {
          existingYaml.paths = {};
        }
        
        // Add or update the endpoint with improved RESTful operations
        const normalizedEndpoint = endpoint.startsWith('/') ? endpoint : `/${endpoint}`;
        
        // Extract resource name from endpoint path
        const resourcePathParts = normalizedEndpoint.split('/').filter(p => p);
        const resourceName = resourcePathParts.length > 0 ? resourcePathParts[resourcePathParts.length - 1] : 'resource';
        const singularResourceName = resourceName.endsWith('s') ? resourceName.slice(0, -1) : resourceName;
        const capitalizedResourceName = singularResourceName.charAt(0).toUpperCase() + singularResourceName.slice(1);
        const resourceIdParam = `${singularResourceName}Id`;
        
        // Setup components section if not exists
        if (!existingYaml.components) {
          existingYaml.components = {};
        }
        if (!existingYaml.components.schemas) {
          existingYaml.components.schemas = {};
        }
        if (!existingYaml.components.responses) {
          existingYaml.components.responses = {};
        }

        // Create common response components
        if (!existingYaml.components.responses['NotFound']) {
          existingYaml.components.responses['NotFound'] = {
            description: 'The requested resource was not found',
            content: {
              'application/json': {
                schema: {
                  type: 'object',
                  properties: {
                    error: { type: 'string', example: 'Resource not found' },
                    status: { type: 'integer', example: 404 }
                  }
                }
              }
            }
          };
        }
        
        if (!existingYaml.components.responses['BadRequest']) {
          existingYaml.components.responses['BadRequest'] = {
            description: 'The request was invalid',
            content: {
              'application/json': {
                schema: {
                  type: 'object',
                  properties: {
                    error: { type: 'string', example: 'Invalid request' },
                    status: { type: 'integer', example: 400 },
                    details: {
                      type: 'object',
                      additionalProperties: true
                    }
                  }
                }
              }
            }
          };
        }

        // Create resource schema if not exists
        if (!existingYaml.components.schemas[capitalizedResourceName]) {
          existingYaml.components.schemas[capitalizedResourceName] = {
            type: 'object',
            properties: {
              id: { type: 'string', description: 'Unique identifier' },
              name: { type: 'string', description: 'Resource name' },
              description: { type: 'string', description: 'Resource description' },
              createdAt: { type: 'string', format: 'date-time', description: 'Creation timestamp' },
              updatedAt: { type: 'string', format: 'date-time', description: 'Last update timestamp' }
            },
            required: ['id', 'name']
          };
        }

        // Create collection response schema
        const collectionName = `${capitalizedResourceName}Collection`;
        if (!existingYaml.components.schemas[collectionName]) {
          existingYaml.components.schemas[collectionName] = {
            type: 'object',
            properties: {
              items: {
                type: 'array',
                items: {
                  $ref: `#/components/schemas/${capitalizedResourceName}`
                }
              },
              total: { type: 'integer' },
              page: { type: 'integer' },
              pageSize: { type: 'integer' },
              pageCount: { type: 'integer' }
            },
            required: ['items']
          };
        }

        // Create request body schema
        const createRequestName = `Create${capitalizedResourceName}Request`;
        if (!existingYaml.components.schemas[createRequestName]) {
          existingYaml.components.schemas[createRequestName] = {
            type: 'object',
            properties: {
              name: { type: 'string', description: 'Resource name' },
              description: { type: 'string', description: 'Resource description' }
            },
            required: ['name']
          };
        }
        
        const updateRequestName = `Update${capitalizedResourceName}Request`;
        if (!existingYaml.components.schemas[updateRequestName]) {
          existingYaml.components.schemas[updateRequestName] = {
            type: 'object',
            properties: {
              name: { type: 'string', description: 'Resource name' },
              description: { type: 'string', description: 'Resource description' }
            }
          };
        }

        // Ensure endpoint paths exist
        if (!existingYaml.paths[normalizedEndpoint]) {
          existingYaml.paths[normalizedEndpoint] = {};
        }

        // Add RESTful operations for collection endpoint (e.g. /resources)
        
        // GET collection - List resources
        existingYaml.paths[normalizedEndpoint].get = {
          summary: `List all ${resourceName}`,
          description: `Returns a collection of ${resourceName}`,
          tags: [capitalizedResourceName],
          parameters: [
            {
              in: 'query',
              name: 'page',
              schema: { type: 'integer', default: 1 },
              description: 'Page number'
            },
            {
              in: 'query',
              name: 'pageSize',
              schema: { type: 'integer', default: 20 },
              description: 'Number of items per page'
            }
          ],
          responses: {
            '200': {
              description: 'List of resources',
              content: {
                'application/json': {
                  schema: {
                    $ref: `#/components/schemas/${collectionName}`
                  }
                }
              }
            }
          }
        };

        // POST collection - Create resource
        existingYaml.paths[normalizedEndpoint].post = {
          summary: `Create a new ${singularResourceName}`,
          description: `Creates a new ${singularResourceName} resource`,
          tags: [capitalizedResourceName],
          requestBody: {
            required: true,
            content: {
              'application/json': {
                schema: {
                  $ref: `#/components/schemas/${createRequestName}`
                }
              }
            }
          },
          responses: {
            '201': {
              description: 'Resource created successfully',
              content: {
                'application/json': {
                  schema: {
                    $ref: `#/components/schemas/${capitalizedResourceName}`
                  }
                }
              }
            },
            '400': {
              $ref: '#/components/responses/BadRequest'
            }
          }
        };

        // Add paths for item operations (e.g., /resources/{id})
        const itemPath = `${normalizedEndpoint}/{${resourceIdParam}}`;
        if (!existingYaml.paths[itemPath]) {
          existingYaml.paths[itemPath] = {};
        }

        // GET item - Get resource by ID
        existingYaml.paths[itemPath].get = {
          summary: `Get a ${singularResourceName} by ID`,
          description: `Returns a single ${singularResourceName} by ID`,
          tags: [capitalizedResourceName],
          parameters: [
            {
              in: 'path',
              name: resourceIdParam,
              required: true,
              schema: { type: 'string' },
              description: `ID of the ${singularResourceName} to retrieve`
            }
          ],
          responses: {
            '200': {
              description: 'Resource retrieved successfully',
              content: {
                'application/json': {
                  schema: {
                    $ref: `#/components/schemas/${capitalizedResourceName}`
                  }
                }
              }
            },
            '404': {
              $ref: '#/components/responses/NotFound'
            }
          }
        };

        // PUT item - Update resource
        existingYaml.paths[itemPath].put = {
          summary: `Update a ${singularResourceName}`,
          description: `Updates an existing ${singularResourceName}`,
          tags: [capitalizedResourceName],
          parameters: [
            {
              in: 'path',
              name: resourceIdParam,
              required: true,
              schema: { type: 'string' },
              description: `ID of the ${singularResourceName} to update`
            }
          ],
          requestBody: {
            required: true,
            content: {
              'application/json': {
                schema: {
                  $ref: `#/components/schemas/${updateRequestName}`
                }
              }
            }
          },
          responses: {
            '200': {
              description: 'Resource updated successfully',
              content: {
                'application/json': {
                  schema: {
                    $ref: `#/components/schemas/${capitalizedResourceName}`
                  }
                }
              }
            },
            '400': {
              $ref: '#/components/responses/BadRequest'
            },
            '404': {
              $ref: '#/components/responses/NotFound'
            }
          }
        };

        // DELETE item - Delete resource
        existingYaml.paths[itemPath].delete = {
          summary: `Delete a ${singularResourceName}`,
          description: `Deletes a ${singularResourceName}`,
          tags: [capitalizedResourceName],
          parameters: [
            {
              in: 'path',
              name: resourceIdParam,
              required: true,
              schema: { type: 'string' },
              description: `ID of the ${singularResourceName} to delete`
            }
          ],
          responses: {
            '204': {
              description: 'Resource deleted successfully'
            },
            '404': {
              $ref: '#/components/responses/NotFound'
            }
          }
        };

        // Create specs directory with proper error handling
        const specDir = projectDir ?
          path.resolve(repoRoot, projectDir) :
          path.join(repoRoot, 'specs');
        try {
          if (!fs.existsSync(specDir)) {
            fs.mkdirSync(specDir, { recursive: true, mode: 0o755 });
          }
        } catch (err: any) {
          console.error('Error creating specs directory:', err);
          throw new Error(`Failed to create specs directory: ${err.message}`);
        }
        
        // Write updated YAML with proper error handling
        try {
          fs.writeFileSync(vibeYamlPath, yaml.dump(existingYaml), { mode: 0o644 });
        } catch (err: any) {
          console.error('Error writing vibe.yaml:', err);
          throw new Error(`Failed to write vibe.yaml: ${err.message}`);
        }
        
        // Generate timestamp and create spec file with improved path handling
        const timestamp = new Date().toISOString().replace(/:/g, '-');
        // Remove leading slashes and replace problematic characters
        const safeEndpoint = normalizedEndpoint.replace(/^\/+/, '').replace(/[\/\\:]/g, '-');
        const specFile = path.join(specDir, `${safeEndpoint}-${timestamp}.json`);
        
        // Generate a detailed spec based on the endpoint and summary (using existing function)
        const spec = generateDetailedSpec(endpoint, summary);
        
        // Write the spec to file with better error handling
        try {
          fs.writeFileSync(specFile, JSON.stringify(spec, null, 2), { mode: 0o644 });
        } catch (err: any) {
          console.error('Error writing spec file:', err);
          throw new Error(`Failed to write spec file: ${err.message}`);
        }
        
        // Return relative paths for better user experience
        const relativeVibeYamlPath = path.relative(baseDir, vibeYamlPath);
        const relativeSpecFile = path.relative(baseDir, specFile);
        
        return {
          content: [
            { 
              type: 'text', 
              text: `Updated OpenAPI spec in ${relativeVibeYamlPath} and created detailed spec in ${relativeSpecFile}` 
            }
          ]
        };
      } catch (error) {
        console.error(`Error in grow_spec tool: ${error}`);
        return {
          content: [
            { 
              type: 'text', 
              text: `Error generating spec: ${error instanceof Error ? error.message : String(error)}` 
            }
          ],
          isError: true
        };
      }
    }
  );
}

/**
 * Generate a detailed specification based on the endpoint and summary
 */
function generateDetailedSpec(endpoint: string, summary: string): any {
  // Extract feature keywords from the summary
  const hasMultiTaskSpecs = /multi-task|multiple tasks|subtasks/i.test(summary);
  const hasMetadata = /metadata|task metadata|data fields/i.test(summary);
  const hasRefineSpec = /refine[_ -]spec|spec refinement/i.test(summary);
  const hasNotifications = /notification|alerts|user notice/i.test(summary);
  const hasDocumentation = /documentation|docs|guides/i.test(summary);
  
  // Build features array based on detected keywords
  const features = [];
  
  if (hasMultiTaskSpecs) {
    features.push({
      "name": "multi-task-specs",
      "description": "Support for defining complex tasks with multiple subtasks and dependencies",
      "details": {
        "structure": {
          "tasks": "Array of task objects that can be executed in sequence or parallel",
          "dependencies": "Graph representation of inter-task dependencies",
          "globalParams": "Parameters shared across all tasks in the spec"
        },
        "implementation": {
          "fileFormat": "Extended JSON format with task definitions",
          "scheduler": "Task execution with dependency resolution",
          "validation": "Schema-based validation of task structures"
        }
      }
    });
  }
  
  if (hasMetadata) {
    features.push({
      "name": "task-metadata",
      "description": "Extended metadata for task tracking, visualization, and management",
      "details": {
        "fields": {
          "owner": "Person responsible for the task",
          "priority": "Task importance (low, medium, high, critical)",
          "estimatedTime": "Expected completion time",
          "status": "Current execution state",
          "tags": "Categorization and filtering"
        },
        "capabilities": {
          "filtering": "Query tasks by metadata",
          "reporting": "Generate status reports based on metadata",
          "visualization": "Create dependency and status charts"
        }
      }
    });
  }
  
  if (hasRefineSpec) {
    features.push({
      "name": "refine-spec-tool",
      "description": "Tool for iteratively refining and updating task specifications",
      "details": {
        "operations": {
          "add": "Add new tasks to existing specs",
          "update": "Modify existing task definitions",
          "remove": "Remove tasks from specs",
          "reorder": "Change task execution order"
        },
        "intelligence": {
          "suggestions": "Smart suggestions for task refinement",
          "validation": "Verify spec integrity after changes",
          "history": "Track changes to specs over time"
        }
      }
    });
  }
  
  if (hasNotifications) {
    features.push({
      "name": "user-notifications",
      "description": "System for notifying users about task status changes and events",
      "details": {
        "channels": {
          "inApp": "Notifications within the Carrot UI",
          "email": "Email notifications for important events",
          "webhook": "Custom webhook integration"
        },
        "events": {
          "taskCompletion": "When tasks are completed",
          "taskFailure": "When tasks encounter errors",
          "progressUpdates": "Periodic updates on long-running tasks",
          "approvalRequests": "When user input is needed"
        },
        "preferences": {
          "perUser": "User-specific notification settings",
          "perProject": "Project-level notification rules"
        }
      }
    });
  }
  
  if (hasDocumentation) {
    features.push({
      "name": "documentation",
      "description": "Comprehensive documentation for Carrot features and APIs",
      "details": {
        "components": {
          "userGuide": "End-user documentation for Carrot",
          "developerDocs": "API documentation for developers",
          "tutorials": "Step-by-step guides for common workflows",
          "examples": "Sample projects and configurations"
        },
        "formats": {
          "markdown": "Source format for all documentation",
          "html": "Generated web documentation",
          "pdf": "Downloadable reference guides"
        },
        "infrastructure": {
          "docSite": "Documentation website with search",
          "versionControl": "Documentation versioned with code",
          "contributionFlow": "Process for community contributions"
        }
      }
    });
  }
  
  // If no specific features were detected, include all by default
  if (features.length === 0) {
    return generateFullSpec(endpoint, summary);
  }
  
  // Create implementation phases based on detected features
  const implementationPhases = generateImplementationPhases(features);
  
  // Return the complete spec
  return {
    endpoint,
    summary,
    createdAt: new Date().toISOString(),
    features,
    implementation: implementationPhases
  };
}

/**
 * Generate implementation phases based on detected features
 */
function generateImplementationPhases(features: any[]): any {
  const featureNames = features.map(f => f.name);
  
  // Design phase tasks
  const designTasks = [];
  if (featureNames.includes('multi-task-specs')) {
    designTasks.push("Create detailed schemas for multi-task specs");
  }
  if (featureNames.includes('task-metadata')) {
    designTasks.push("Design API endpoints for task metadata");
  }
  if (featureNames.includes('user-notifications')) {
    designTasks.push("Plan user notification system architecture");
  }
  if (featureNames.includes('documentation')) {
    designTasks.push("Outline documentation structure");
  }
  
  // Implementation phase tasks
  const implementationTasks = [];
  if (featureNames.includes('multi-task-specs')) {
    implementationTasks.push("Develop core multi-task spec functionality");
  }
  if (featureNames.includes('refine-spec-tool')) {
    implementationTasks.push("Build refine-spec tool backend");
  }
  if (featureNames.includes('user-notifications')) {
    implementationTasks.push("Implement notification system");
  }
  if (featureNames.includes('documentation')) {
    implementationTasks.push("Create documentation infrastructure");
  }
  
  // Testing phase tasks
  const testingTasks = ["Unit test all new components"];
  if (featureNames.includes('user-notifications')) {
    testingTasks.push("Integration testing of notification system");
  }
  if (featureNames.includes('refine-spec-tool')) {
    testingTasks.push("User testing of refine-spec tool");
  }
  if (featureNames.includes('documentation')) {
    testingTasks.push("Documentation review");
  }
  
  // Deployment phase tasks
  const deploymentTasks = [
    "Release new features",
    "Publish documentation",
    "Monitor system performance",
    "Gather user feedback"
  ];
  
  return {
    phases: [
      {
        name: "Design",
        tasks: designTasks.length > 0 ? designTasks : ["Design system architecture"],
        deliverables: ["Design documents", "API specifications", "Schema definitions"]
      },
      {
        name: "Implementation",
        tasks: implementationTasks.length > 0 ? implementationTasks : ["Implement core functionality"],
        deliverables: ["Functional code", "Initial documentation", "Test suite"]
      },
      {
        name: "Testing",
        tasks: testingTasks,
        deliverables: ["Test reports", "User feedback", "Documentation updates"]
      },
      {
        name: "Deployment",
        tasks: deploymentTasks,
        deliverables: ["Production release", "Public documentation", "Feedback analysis"]
      }
    ],
    dependencies: {
      external: ["MCP SDK", "Documentation generation tools", "Notification service"],
      internal: ["Existing task execution system", "User management", "API gateway"]
    }
  };
}

/**
 * Generate a full spec with all features when no specific features are detected
 */
function generateFullSpec(endpoint: string, summary: string): any {
  return {
    endpoint,
    summary,
    createdAt: new Date().toISOString(),
    features: [
      {
        "name": "multi-task-specs",
        "description": "Support for defining complex tasks with multiple subtasks and dependencies",
        "details": {
          "structure": {
            "tasks": "Array of task objects that can be executed in sequence or parallel",
            "dependencies": "Graph representation of inter-task dependencies",
            "globalParams": "Parameters shared across all tasks in the spec"
          },
          "implementation": {
            "fileFormat": "Extended JSON format with task definitions",
            "scheduler": "Task execution with dependency resolution",
            "validation": "Schema-based validation of task structures"
          }
        }
      },
      {
        "name": "task-metadata",
        "description": "Extended metadata for task tracking, visualization, and management",
        "details": {
          "fields": {
            "owner": "Person responsible for the task",
            "priority": "Task importance (low, medium, high, critical)",
            "estimatedTime": "Expected completion time",
            "status": "Current execution state",
            "tags": "Categorization and filtering"
          },
          "capabilities": {
            "filtering": "Query tasks by metadata",
            "reporting": "Generate status reports based on metadata",
            "visualization": "Create dependency and status charts"
          }
        }
      },
      {
        "name": "refine-spec-tool",
        "description": "Tool for iteratively refining and updating task specifications",
        "details": {
          "operations": {
            "add": "Add new tasks to existing specs",
            "update": "Modify existing task definitions",
            "remove": "Remove tasks from specs",
            "reorder": "Change task execution order"
          },
          "intelligence": {
            "suggestions": "Smart suggestions for task refinement",
            "validation": "Verify spec integrity after changes",
            "history": "Track changes to specs over time"
          }
        }
      },
      {
        "name": "user-notifications",
        "description": "System for notifying users about task status changes and events",
        "details": {
          "channels": {
            "inApp": "Notifications within the Carrot UI",
            "email": "Email notifications for important events",
            "webhook": "Custom webhook integration"
          },
          "events": {
            "taskCompletion": "When tasks are completed",
            "taskFailure": "When tasks encounter errors",
            "progressUpdates": "Periodic updates on long-running tasks",
            "approvalRequests": "When user input is needed"
          },
          "preferences": {
            "perUser": "User-specific notification settings",
            "perProject": "Project-level notification rules"
          }
        }
      },
      {
        "name": "documentation",
        "description": "Comprehensive documentation for Carrot features and APIs",
        "details": {
          "components": {
            "userGuide": "End-user documentation for Carrot",
            "developerDocs": "API documentation for developers",
            "tutorials": "Step-by-step guides for common workflows",
            "examples": "Sample projects and configurations"
          },
          "formats": {
            "markdown": "Source format for all documentation",
            "html": "Generated web documentation",
            "pdf": "Downloadable reference guides"
          },
          "infrastructure": {
            "docSite": "Documentation website with search",
            "versionControl": "Documentation versioned with code",
            "contributionFlow": "Process for community contributions"
          }
        }
      }
    ],
    implementation: {
      phases: [
        {
          name: "Design",
          tasks: [
            "Create detailed schemas for multi-task specs",
            "Design API endpoints for task metadata",
            "Plan user notification system architecture",
            "Outline documentation structure"
          ],
          deliverables: ["Design documents", "API specifications", "Schema definitions"]
        },
        {
          name: "Implementation",
          tasks: [
            "Develop core multi-task spec functionality",
            "Build refine-spec tool backend",
            "Implement notification system",
            "Create documentation infrastructure"
          ],
          deliverables: ["Functional code", "Initial documentation", "Test suite"]
        },
        {
          name: "Testing",
          tasks: [
            "Unit test all new components",
            "Integration testing of notification system",
            "User testing of refine-spec tool",
            "Documentation review"
          ],
          deliverables: ["Test reports", "User feedback", "Documentation updates"]
        },
        {
          name: "Deployment",
          tasks: [
            "Release new features",
            "Publish documentation",
            "Monitor system performance",
            "Gather user feedback"
          ],
          deliverables: ["Production release", "Public documentation", "Feedback analysis"]
        }
      ],
      dependencies: {
        external: ["MCP SDK", "Documentation generation tools", "Notification service"],
        internal: ["Existing task execution system", "User management", "API gateway"]
      }
    }
  };
}

/**
 * Extract features from the summary text
 * This function attempts to identify key features mentioned in the summary
 * and generates structured metadata for each identified feature
 */
function extractFeaturesFromSummary(summary: string): any[] {
  // Convert summary to lowercase and split by common separators
  const words = summary.toLowerCase().split(/[,.:;]|\sand\s|\swith\s/);
  
  // Define feature patterns to look for
  const featurePatterns = [
    { 
      pattern: /multi-task|multiple tasks|task management/, 
      name: 'multi-task-specs',
      description: 'Support for defining complex tasks with multiple subtasks and dependencies',
      template: {
        structure: {
          tasks: 'Array of task objects that can be executed in sequence or parallel',
          dependencies: 'Graph representation of inter-task dependencies',
          globalParams: 'Parameters shared across all tasks in the spec'
        }
      }
    },
    { 
      pattern: /metadata|task metadata|data fields/, 
      name: 'task-metadata',
      description: 'Extended metadata for task tracking, visualization, and management',
      template: {
        fields: {
          owner: 'Person responsible for the task',
          priority: 'Task importance (low, medium, high, critical)',
          status: 'Current execution state'
        }
      }
    },
    { 
      pattern: /refine[_ -]spec|spec refinement|update specs/, 
      name: 'refine-spec-tool',
      description: 'Tool for iteratively refining and updating task specifications',
      template: {
        operations: {
          add: 'Add new tasks to existing specs',
          update: 'Modify existing task definitions',
          remove: 'Remove tasks from specs'
        }
      }
    },
    { 
      pattern: /notification|alerts|user notice/, 
      name: 'user-notifications',
      description: 'System for notifying users about task status changes and events',
      template: {
        channels: {
          inApp: 'Notifications within the Carrot UI',
          email: 'Email notifications for important events'
        }
      }
    },
    { 
      pattern: /documentation|docs|guides/, 
      name: 'documentation',
      description: 'Comprehensive documentation for Carrot features and APIs',
      template: {
        components: {
          userGuide: 'End-user documentation for Carrot',
          developerDocs: 'API documentation for developers'
        }
      }
    }
  ];
  
  // Identify features mentioned in the summary
  const identifiedFeatures = [];
  
  for (const { pattern, name, description, template } of featurePatterns) {
    if (words.some(word => pattern.test(word))) {
      identifiedFeatures.push({
        name,
        description,
        details: template
      });
    }
  }
  
  return identifiedFeatures;
} 