import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { z } from 'zod';
import * as fs from 'fs';
import * as path from 'path';
import * as yaml from 'js-yaml';

/**
 * Configure grow_spec tool for adding entries to the spec repository
 */
export function growSpecTool(server: McpServer, repoRoot: string): void {
  console.log('Initializing grow_spec tool with repo root:', repoRoot);
  
  server.tool(
    'grow_spec',
    {
      endpoint: z.string().min(1).describe('The API endpoint path to generate a specification for'),
      summary: z.string().min(1).describe('A brief summary of the endpoint\'s purpose'),
      projectDir: z.string().optional().describe('Target project directory where specs should be generated. If not provided, will use current directory.')
    },
    async ({ endpoint, summary, projectDir }: { endpoint: string; summary: string; projectDir?: string }) => {
      try {
        console.log(`grow_spec tool called with endpoint: ${endpoint}, summary: ${summary}, projectDir: ${projectDir}`);
        
        // Use the repository root as a stable base directory so that subsequent
        // calls do not depend on whatever the current working directory might
        // have been changed to elsewhere in the application lifecycle.
        const baseDir = repoRoot;
        console.log('Base directory:', baseDir);
        
        // Resolve target directory with better path handling
        const targetDir = projectDir ? 
          (path.isAbsolute(projectDir) ? 
            // If absolute path, validate it's a user directory (not system)
            (projectDir.startsWith('/Users') || projectDir.startsWith('/home') ? projectDir : path.join(baseDir, projectDir)) :
            // If relative path, resolve from the repo root
            path.resolve(baseDir, projectDir)
          ) : 
          baseDir;
        
        console.log(`Using target directory: ${targetDir}`);

        // Enhanced safety checks for system directories
        if (targetDir === '/' || 
            targetDir.startsWith('/usr') || 
            targetDir.startsWith('/etc') || 
            targetDir.startsWith('/var') || 
            targetDir.startsWith('/tmp')) {
          throw new Error(`Cannot write to system directory: ${targetDir}`);
        }

        // Ensure target directory exists with logging
        if (!fs.existsSync(targetDir)) {
          console.log(`Creating target directory ${targetDir}...`);
          try {
            fs.mkdirSync(targetDir, { recursive: true });
          } catch (err: any) {
            console.error(`Failed to create directory ${targetDir}:`, err);
            throw new Error(`Failed to create directory ${targetDir}: ${err.message}`);
          }
        }
        
        // vibe.yaml is pinned to the repo root – never inside projectDir.
        const vibeYamlPath = path.join(repoRoot, 'vibe.yaml');
        
        // Create or read vibe.yaml with proper error handling
        let existingYaml;
        if (fs.existsSync(vibeYamlPath)) {
          try {
            existingYaml = yaml.load(fs.readFileSync(vibeYamlPath, 'utf8')) as any;
          } catch (err: any) {
            console.error(`Error reading ${vibeYamlPath}:`, err);
            throw new Error(`Failed to read ${vibeYamlPath}: ${err.message}`);
          }
        } else {
          // Create initial OpenAPI spec
          existingYaml = {
            openapi: '3.0.0',
            info: {
              title: 'API Specification',
              version: '1.0.0',
              description: 'API specification generated by Carrot MCP'
            },
            paths: {}
          };
        }
        
        // Ensure paths object exists
        if (!existingYaml.paths) {
          existingYaml.paths = {};
        }
        
        // Add or update the endpoint with improved RESTful operations
        const normalizedEndpoint = endpoint.startsWith('/') ? endpoint : `/${endpoint}`;
        
        // Extract resource name from endpoint path
        const resourcePathParts = normalizedEndpoint.split('/').filter(p => p);
        const resourceName = resourcePathParts.length > 0 ? resourcePathParts[resourcePathParts.length - 1] : 'resource';
        const singularResourceName = resourceName.endsWith('s') ? resourceName.slice(0, -1) : resourceName;
        const capitalizedResourceName = singularResourceName.charAt(0).toUpperCase() + singularResourceName.slice(1);
        const resourceIdParam = `${singularResourceName}Id`;
        
        // Setup components section if not exists
        if (!existingYaml.components) {
          existingYaml.components = {};
        }
        if (!existingYaml.components.schemas) {
          existingYaml.components.schemas = {};
        }
        if (!existingYaml.components.responses) {
          existingYaml.components.responses = {};
        }

        // Create common response components
        if (!existingYaml.components.responses['NotFound']) {
          existingYaml.components.responses['NotFound'] = {
            description: 'The requested resource was not found',
            content: {
              'application/json': {
                schema: {
                  type: 'object',
                  properties: {
                    error: { type: 'string', example: 'Resource not found' },
                    status: { type: 'integer', example: 404 }
                  }
                }
              }
            }
          };
        }
        
        if (!existingYaml.components.responses['BadRequest']) {
          existingYaml.components.responses['BadRequest'] = {
            description: 'The request was invalid',
            content: {
              'application/json': {
                schema: {
                  type: 'object',
                  properties: {
                    error: { type: 'string', example: 'Invalid request' },
                    status: { type: 'integer', example: 400 },
                    details: {
                      type: 'object',
                      additionalProperties: true
                    }
                  }
                }
              }
            }
          };
        }

        // Create resource schema if not exists
        if (!existingYaml.components.schemas[capitalizedResourceName]) {
          existingYaml.components.schemas[capitalizedResourceName] = {
            type: 'object',
            properties: {
              id: { type: 'string', description: 'Unique identifier' },
              name: { type: 'string', description: 'Resource name' },
              description: { type: 'string', description: 'Resource description' },
              createdAt: { type: 'string', format: 'date-time', description: 'Creation timestamp' },
              updatedAt: { type: 'string', format: 'date-time', description: 'Last update timestamp' }
            },
            required: ['id', 'name']
          };
        }

        // Create collection response schema
        const collectionName = `${capitalizedResourceName}Collection`;
        if (!existingYaml.components.schemas[collectionName]) {
          existingYaml.components.schemas[collectionName] = {
            type: 'object',
            properties: {
              items: {
                type: 'array',
                items: {
                  $ref: `#/components/schemas/${capitalizedResourceName}`
                }
              },
              total: { type: 'integer' },
              page: { type: 'integer' },
              pageSize: { type: 'integer' },
              pageCount: { type: 'integer' }
            },
            required: ['items']
          };
        }

        // Create request body schema
        const createRequestName = `Create${capitalizedResourceName}Request`;
        if (!existingYaml.components.schemas[createRequestName]) {
          existingYaml.components.schemas[createRequestName] = {
            type: 'object',
            properties: {
              name: { type: 'string', description: 'Resource name' },
              description: { type: 'string', description: 'Resource description' }
            },
            required: ['name']
          };
        }
        
        const updateRequestName = `Update${capitalizedResourceName}Request`;
        if (!existingYaml.components.schemas[updateRequestName]) {
          existingYaml.components.schemas[updateRequestName] = {
            type: 'object',
            properties: {
              name: { type: 'string', description: 'Resource name' },
              description: { type: 'string', description: 'Resource description' }
            }
          };
        }

        // Ensure endpoint paths exist
        if (!existingYaml.paths[normalizedEndpoint]) {
          existingYaml.paths[normalizedEndpoint] = {};
        }

        // Add RESTful operations for collection endpoint (e.g. /resources)
        
        // GET collection - List resources
        existingYaml.paths[normalizedEndpoint].get = {
          summary: `List all ${resourceName}`,
          description: `Returns a collection of ${resourceName}`,
          tags: [capitalizedResourceName],
          parameters: [
            {
              in: 'query',
              name: 'page',
              schema: { type: 'integer', default: 1 },
              description: 'Page number'
            },
            {
              in: 'query',
              name: 'pageSize',
              schema: { type: 'integer', default: 20 },
              description: 'Number of items per page'
            }
          ],
          responses: {
            '200': {
              description: 'List of resources',
              content: {
                'application/json': {
                  schema: {
                    $ref: `#/components/schemas/${collectionName}`
                  }
                }
              }
            }
          }
        };

        // POST collection - Create resource
        existingYaml.paths[normalizedEndpoint].post = {
          summary: `Create a new ${singularResourceName}`,
          description: `Creates a new ${singularResourceName} resource`,
          tags: [capitalizedResourceName],
          requestBody: {
            required: true,
            content: {
              'application/json': {
                schema: {
                  $ref: `#/components/schemas/${createRequestName}`
                }
              }
            }
          },
          responses: {
            '201': {
              description: 'Resource created successfully',
              content: {
                'application/json': {
                  schema: {
                    $ref: `#/components/schemas/${capitalizedResourceName}`
                  }
                }
              }
            },
            '400': {
              $ref: '#/components/responses/BadRequest'
            }
          }
        };

        // Add paths for item operations (e.g., /resources/{id})
        const itemPath = `${normalizedEndpoint}/{${resourceIdParam}}`;
        if (!existingYaml.paths[itemPath]) {
          existingYaml.paths[itemPath] = {};
        }

        // GET item - Get resource by ID
        existingYaml.paths[itemPath].get = {
          summary: `Get a ${singularResourceName} by ID`,
          description: `Returns a single ${singularResourceName} by ID`,
          tags: [capitalizedResourceName],
          parameters: [
            {
              in: 'path',
              name: resourceIdParam,
              required: true,
              schema: { type: 'string' },
              description: `ID of the ${singularResourceName} to retrieve`
            }
          ],
          responses: {
            '200': {
              description: 'Resource retrieved successfully',
              content: {
                'application/json': {
                  schema: {
                    $ref: `#/components/schemas/${capitalizedResourceName}`
                  }
                }
              }
            },
            '404': {
              $ref: '#/components/responses/NotFound'
            }
          }
        };

        // PUT item - Update resource
        existingYaml.paths[itemPath].put = {
          summary: `Update a ${singularResourceName}`,
          description: `Updates an existing ${singularResourceName}`,
          tags: [capitalizedResourceName],
          parameters: [
            {
              in: 'path',
              name: resourceIdParam,
              required: true,
              schema: { type: 'string' },
              description: `ID of the ${singularResourceName} to update`
            }
          ],
          requestBody: {
            required: true,
            content: {
              'application/json': {
                schema: {
                  $ref: `#/components/schemas/${updateRequestName}`
                }
              }
            }
          },
          responses: {
            '200': {
              description: 'Resource updated successfully',
              content: {
                'application/json': {
                  schema: {
                    $ref: `#/components/schemas/${capitalizedResourceName}`
                  }
                }
              }
            },
            '400': {
              $ref: '#/components/responses/BadRequest'
            },
            '404': {
              $ref: '#/components/responses/NotFound'
            }
          }
        };

        // DELETE item - Delete resource
        existingYaml.paths[itemPath].delete = {
          summary: `Delete a ${singularResourceName}`,
          description: `Deletes a ${singularResourceName}`,
          tags: [capitalizedResourceName],
          parameters: [
            {
              in: 'path',
              name: resourceIdParam,
              required: true,
              schema: { type: 'string' },
              description: `ID of the ${singularResourceName} to delete`
            }
          ],
          responses: {
            '204': {
              description: 'Resource deleted successfully'
            },
            '404': {
              $ref: '#/components/responses/NotFound'
            }
          }
        };

        // Create specs directory with proper error handling and intelligent routing
        const specDir = projectDir ?
          path.resolve(repoRoot, projectDir) :
          determineSpecDirectory(repoRoot, normalizedEndpoint);
        
        try {
          if (!fs.existsSync(specDir)) {
            fs.mkdirSync(specDir, { recursive: true, mode: 0o755 });
          }
        } catch (err: any) {
          console.error('Error creating specs directory:', err);
          throw new Error(`Failed to create specs directory: ${err.message}`);
        }
        
        // Write updated YAML with proper error handling
        try {
          fs.writeFileSync(vibeYamlPath, yaml.dump(existingYaml), { mode: 0o644 });
        } catch (err: any) {
          console.error('Error writing vibe.yaml:', err);
          throw new Error(`Failed to write vibe.yaml: ${err.message}`);
        }
        
        // Generate timestamp and create spec file with improved path handling
        const timestamp = new Date().toISOString().replace(/:/g, '-');
        // Remove leading slashes and replace problematic characters
        const safeEndpoint = normalizedEndpoint.replace(/^\/+/, '').replace(/[\/\\:]/g, '-');
        const specFile = path.join(specDir, `${safeEndpoint}-${timestamp}.json`);
        
        // Generate a detailed spec based on the endpoint and summary (using existing function)
        const spec = generateDetailedSpec(endpoint, summary, repoRoot);
        
        // Write the spec to file with better error handling
        try {
          fs.writeFileSync(specFile, JSON.stringify(spec, null, 2), { mode: 0o644 });
        } catch (err: any) {
          console.error('Error writing spec file:', err);
          throw new Error(`Failed to write spec file: ${err.message}`);
        }
        
        // Return relative paths for better user experience
        const relativeVibeYamlPath = path.relative(baseDir, vibeYamlPath);
        const relativeSpecFile = path.relative(baseDir, specFile);
        
        return {
          content: [
            { 
              type: 'text', 
              text: `Updated OpenAPI spec in ${relativeVibeYamlPath} and created detailed spec in ${relativeSpecFile}` 
            }
          ]
        };
      } catch (error) {
        console.error(`Error in grow_spec tool: ${error}`);
        return {
          content: [
            { 
              type: 'text', 
              text: `Error generating spec: ${error instanceof Error ? error.message : String(error)}` 
            }
          ],
          isError: true
        };
      }
    }
  );
}

/**
 * Generate a detailed specification based on the endpoint and summary
 */
function generateDetailedSpec(endpoint: string, summary: string, repoRoot: string): any {
  // Analyze project context for domain intelligence
  const context = analyzeProjectContext(repoRoot, endpoint, summary);
  
  // Generate domain-specific specification
  if (context.domain === 'spotify') {
    return generateSpotifySpec(endpoint, summary, context);
  } else if (context.domain === 'user_management') {
    return generateUserManagementSpec(endpoint, summary, context);
  } else if (context.domain === 'api') {
    return generateAPISpec(endpoint, summary, context);
  }
  
  // Fallback to context-aware generic spec
  return generateContextAwareSpec(endpoint, summary, context);
}

/**
 * Analyze project context to understand domain and existing patterns
 */
function analyzeProjectContext(repoRoot: string, endpoint: string, summary: string): any {
  const context: {
    domain: string;
    patterns: string[];
    existingSchemas: string[];
    projectType: string;
    features: string[];
  } = {
    domain: 'generic',
    patterns: [],
    existingSchemas: [],
    projectType: 'unknown',
    features: []
  };

  try {
    // Analyze endpoint and summary for domain hints
    const endpointLower = endpoint.toLowerCase();
    const summaryLower = summary.toLowerCase();
    
    // Domain detection
    if (endpointLower.includes('spotify') || endpointLower.includes('playlist') || 
        summaryLower.includes('spotify') || summaryLower.includes('playlist') || summaryLower.includes('music')) {
      context.domain = 'spotify';
    } else if (endpointLower.includes('user') || endpointLower.includes('auth') ||
               summaryLower.includes('user') || summaryLower.includes('authentication')) {
      context.domain = 'user_management';
    } else if (endpointLower.includes('api') || summaryLower.includes('api')) {
      context.domain = 'api';
    }

    // Look for existing project structure
    const packageJsonPath = path.join(repoRoot, 'package.json');
    if (fs.existsSync(packageJsonPath)) {
      const packageJson = JSON.parse(fs.readFileSync(packageJsonPath, 'utf8'));
      
      // Detect project type
      if (packageJson.dependencies?.next) {
        context.projectType = 'nextjs';
        context.patterns.push('nextjs_api');
      }
      if (packageJson.dependencies?.zod) {
        context.patterns.push('zod_validation');
      }
      if (packageJson.dependencies?.['spotify-web-api-node']) {
        context.patterns.push('spotify_integration');
      }
    }

    // Look for existing API routes and types
    const apiDir = path.join(repoRoot, 'src/app/api');
    if (fs.existsSync(apiDir)) {
      context.patterns.push('api_routes');
      
      // Scan for existing patterns
      const scanForPatterns = (dir: string) => {
        try {
          const items = fs.readdirSync(dir);
          for (const item of items) {
            const itemPath = path.join(dir, item);
            if (fs.statSync(itemPath).isDirectory()) {
              scanForPatterns(itemPath);
            } else if (item === 'route.ts' || item === 'types.ts') {
              const content = fs.readFileSync(itemPath, 'utf8');
              
              if (content.includes('x-user-id')) {
                context.patterns.push('user_auth_header');
              }
              if (content.includes('NextRequest') && content.includes('NextResponse')) {
                context.patterns.push('nextjs_handlers');
              }
              if (content.includes('playlist')) {
                context.features.push('playlist_management');
              }
              if (content.includes('tracks')) {
                context.features.push('track_management');
              }
            }
          }
        } catch (err) {
          // Ignore scanning errors
        }
      };
      scanForPatterns(apiDir);
    }

    // Look for existing vibe.yaml to understand current API structure
    const vibeYamlPath = path.join(repoRoot, 'vibe.yaml');
    if (fs.existsSync(vibeYamlPath)) {
      try {
        const vibeContent = yaml.load(fs.readFileSync(vibeYamlPath, 'utf8')) as any;
        if (vibeContent?.paths) {
          context.existingSchemas = Object.keys(vibeContent.paths);
          
          // Analyze existing endpoints for patterns
          for (const path of Object.keys(vibeContent.paths)) {
            if (path.includes('playlist')) {
              context.features.push('playlist_api');
            }
            if (path.includes('user')) {
              context.features.push('user_api');
            }
          }
        }
      } catch (err) {
        console.warn('Error parsing vibe.yaml:', err);
      }
    }

  } catch (error) {
    console.warn('Error analyzing project context:', error);
  }

  return context;
}

/**
 * Generate Spotify-specific specification
 */
function generateSpotifySpec(endpoint: string, summary: string, context: any): any {
  const spec = {
    endpoint,
    summary,
    domain: 'spotify',
    createdAt: new Date().toISOString(),
    context: {
      projectType: context.projectType,
      patterns: context.patterns,
      features: context.features
    }
  };

  if (endpoint.includes('playlist')) {
    return {
      ...spec,
      specification: {
        purpose: 'Spotify playlist management endpoint',
        functionality: {
          core: 'Manage user playlists with full CRUD operations',
          features: [
            'Create playlists with metadata (name, description, public/private)',
            'Update playlist properties and track lists',
            'Retrieve playlists with user authorization',
            'Delete playlists with ownership validation',
            'Track management within playlists'
          ],
          authentication: 'User-based via x-user-id header',
          authorization: 'Users can only access their own playlists'
        },
        dataModel: {
          playlist: {
            id: 'Unique playlist identifier (UUID)',
            name: 'Playlist name (max 100 chars)',
            description: 'Optional description (max 300 chars)',
            public: 'Boolean - public visibility',
            collaborative: 'Boolean - collaborative editing',
            userId: 'Owner user ID',
            tracks: 'Array of track objects',
            createdAt: 'ISO timestamp',
            updatedAt: 'ISO timestamp'
          },
          track: {
            id: 'Spotify track ID',
            name: 'Track name',
            artist: 'Artist name',
            duration: 'Duration in seconds',
            addedAt: 'When added to playlist'
          }
        },
        apiOperations: generateSpotifyAPIOperations(endpoint),
        validation: {
          input: [
            'Playlist name required and non-empty',
            'Description max 300 characters',
            'User ID must be valid',
            'Track IDs must be valid Spotify IDs'
          ],
          business: [
            'Users can only modify their own playlists',
            'Playlist names must be unique per user',
            'Maximum 10,000 tracks per playlist'
          ]
        },
        errorHandling: {
          400: 'Invalid request data (validation errors)',
          401: 'Missing or invalid authentication',
          403: 'Unauthorized access to playlist',
          404: 'Playlist not found',
          409: 'Playlist name conflict',
          429: 'Rate limit exceeded',
          500: 'Internal server error'
        }
      },
      implementation: generateSpotifyImplementationPlan(context),
      testing: generateSpotifyTestPlan(endpoint)
    };
  }

  // Default Spotify spec for other endpoints
  return {
    ...spec,
    specification: {
      purpose: `Spotify ${summary}`,
      functionality: {
        core: summary,
        features: ['Integration with Spotify Web API', 'User authentication', 'Error handling'],
        authentication: context.patterns.includes('user_auth_header') ? 'User-based via x-user-id header' : 'To be determined',
        authorization: 'User-specific access control'
      }
    },
    implementation: generateSpotifyImplementationPlan(context),
    testing: generateGenericTestPlan(endpoint, summary)
  };
}

/**
 * Generate Spotify API operations based on endpoint
 */
function generateSpotifyAPIOperations(endpoint: string): any {
  const operations: { [key: string]: any } = {};
  
  if (endpoint.includes('{') && endpoint.includes('}')) {
    // Individual resource endpoint
    operations['GET'] = {
      purpose: 'Retrieve specific playlist',
      parameters: ['playlistId (path)', 'x-user-id (header)'],
      response: 'Full playlist object with tracks',
      authorization: 'Must be playlist owner'
    };
    
    operations['PATCH'] = {
      purpose: 'Update playlist properties',
      parameters: ['playlistId (path)', 'x-user-id (header)', 'update data (body)'],
      response: 'Updated playlist object',
      authorization: 'Must be playlist owner',
      notes: 'Partial updates supported'
    };
    
    operations['DELETE'] = {
      purpose: 'Delete playlist',
      parameters: ['playlistId (path)', 'x-user-id (header)'],
      response: '204 No Content',
      authorization: 'Must be playlist owner'
    };
  } else {
    // Collection endpoint
    operations['GET'] = {
      purpose: 'List user playlists',
      parameters: ['x-user-id (header)', 'page (query)', 'limit (query)'],
      response: 'Paginated list of playlists',
      authorization: 'User-specific playlists only'
    };
    
    operations['POST'] = {
      purpose: 'Create new playlist',
      parameters: ['x-user-id (header)', 'playlist data (body)'],
      response: 'Created playlist object',
      authorization: 'Creates for authenticated user'
    };
  }
  
  return operations;
}

/**
 * Generate Spotify implementation plan
 */
function generateSpotifyImplementationPlan(context: any): any {
  const plan = {
    phases: [
      {
        name: 'Data Layer',
        tasks: [
          'Define playlist and track data models',
          'Set up database schema (if using local storage)',
          'Implement data access layer'
        ],
        deliverables: ['Data models', 'Database schema', 'Repository pattern']
      },
      {
        name: 'API Layer',
        tasks: [
          'Implement route handlers',
          'Add request validation',
          'Implement authentication middleware',
          'Add error handling'
        ],
        deliverables: ['Route handlers', 'Validation schemas', 'Middleware']
      },
      {
        name: 'Integration',
        tasks: [
          'Integrate with Spotify Web API (if needed)',
          'Implement user authorization',
          'Add logging and monitoring'
        ],
        deliverables: ['API integration', 'Auth system', 'Monitoring']
      },
      {
        name: 'Testing & Documentation',
        tasks: [
          'Unit tests for all components',
          'Integration tests',
          'API documentation',
          'User guides'
        ],
        deliverables: ['Test suite', 'Documentation', 'Examples']
      }
    ],
    technologies: generateTechnologyStack(context),
    dependencies: [
      'spotify-web-api-node (if using Spotify API)',
      'zod (for validation)',
      'next (for API routes)',
      'uuid (for ID generation)'
    ]
  };

  return plan;
}

/**
 * Generate technology stack based on context
 */
function generateTechnologyStack(context: any): any {
  const stack: { [key: string]: any } = {
    runtime: 'Node.js',
    framework: context.projectType === 'nextjs' ? 'Next.js API Routes' : 'Express.js',
    validation: context.patterns.includes('zod_validation') ? 'Zod' : 'Joi or custom validation',
    database: 'To be determined (PostgreSQL, MongoDB, or in-memory)',
    authentication: context.patterns.includes('user_auth_header') ? 'Custom header-based' : 'JWT or session-based'
  };

  if (context.patterns.includes('spotify_integration')) {
    stack.external_apis = 'Spotify Web API';
  }

  return stack;
}

/**
 * Generate Spotify test plan
 */
function generateSpotifyTestPlan(endpoint: string): any {
  const testPlan = {
    unitTests: [
      'Playlist data model validation',
      'Route handler logic',
      'Authentication middleware',
      'Error handling functions'
    ],
    integrationTests: [
      'End-to-end playlist CRUD operations',
      'User authorization flows',
      'Error response handling',
      'Data persistence verification'
    ],
    testScenarios: [] as any[]
  };

  if (endpoint.includes('playlist')) {
    testPlan.testScenarios = [
      {
        scenario: 'Create playlist success',
        given: 'Valid user and playlist data',
        when: 'POST request to create playlist',
        then: 'Playlist created with 201 status'
      },
      {
        scenario: 'Update playlist unauthorized',
        given: 'User tries to update another user\'s playlist',
        when: 'PATCH request with different user ID',
        then: '403 Forbidden response'
      },
      {
        scenario: 'Get playlist not found',
        given: 'Non-existent playlist ID',
        when: 'GET request for playlist',
        then: '404 Not Found response'
      },
      {
        scenario: 'Delete playlist success',
        given: 'User owns the playlist',
        when: 'DELETE request for playlist',
        then: 'Playlist deleted with 204 status'
      }
    ];
  }

  return testPlan;
}

/**
 * Generate user management specification
 */
function generateUserManagementSpec(endpoint: string, summary: string, context: any): any {
  return {
    endpoint,
    summary,
    domain: 'user_management',
    createdAt: new Date().toISOString(),
    specification: {
      purpose: `User management: ${summary}`,
      functionality: {
        core: 'User account and authentication management',
        features: ['User registration', 'Authentication', 'Profile management', 'Authorization'],
        security: 'Password hashing, session management, role-based access'
      }
    },
    implementation: generateUserImplementationPlan(context),
    testing: generateGenericTestPlan(endpoint, summary)
  };
}

/**
 * Generate API specification
 */
function generateAPISpec(endpoint: string, summary: string, context: any): any {
  return {
    endpoint,
    summary,
    domain: 'api',
    createdAt: new Date().toISOString(),
    specification: {
      purpose: `API endpoint: ${summary}`,
      functionality: {
        core: summary,
        features: ['RESTful operations', 'Request validation', 'Error handling'],
        patterns: context.patterns
      }
    },
    implementation: generateAPIImplementationPlan(context),
    testing: generateGenericTestPlan(endpoint, summary)
  };
}

/**
 * Generate context-aware specification
 */
function generateContextAwareSpec(endpoint: string, summary: string, context: any): any {
  return {
    endpoint,
    summary,
    domain: context.domain,
    createdAt: new Date().toISOString(),
    context: {
      projectType: context.projectType,
      patterns: context.patterns,
      features: context.features,
      existingSchemas: context.existingSchemas
    },
    specification: {
      purpose: summary,
      functionality: {
        core: summary,
        features: extractFeaturesFromSummary(summary),
        patterns: context.patterns
      },
      recommendations: generateRecommendations(context, endpoint, summary)
    },
    implementation: generateGenericImplementationPlan(context),
    testing: generateGenericTestPlan(endpoint, summary)
  };
}

/**
 * Generate recommendations based on context
 */
function generateRecommendations(context: any, endpoint: string, summary: string): string[] {
  const recommendations = [];

  if (context.projectType === 'nextjs') {
    recommendations.push('Use Next.js API route patterns with proper TypeScript types');
  }

  if (context.patterns.includes('zod_validation')) {
    recommendations.push('Implement Zod schemas for request validation');
  }

  if (context.patterns.includes('user_auth_header')) {
    recommendations.push('Follow existing authentication pattern with x-user-id header');
  }

  if (context.features.includes('playlist_management')) {
    recommendations.push('Ensure consistency with existing playlist API patterns');
  }

  if (endpoint.includes('{') && endpoint.includes('}')) {
    recommendations.push('Implement proper path parameter validation');
    recommendations.push('Add 404 handling for non-existent resources');
  }

  recommendations.push('Add comprehensive error handling and logging');
  recommendations.push('Include unit and integration tests');
  recommendations.push('Document API with OpenAPI/Swagger');

  return recommendations;
}

/**
 * Generate implementation plans for different domains
 */
function generateUserImplementationPlan(context: any): any {
  return {
    phases: [
      {
        name: 'Authentication Setup',
        tasks: ['Set up user model', 'Implement password hashing', 'Create session management'],
        deliverables: ['User schema', 'Auth middleware', 'Session store']
      },
      {
        name: 'API Implementation',
        tasks: ['Create user routes', 'Add validation', 'Implement CRUD operations'],
        deliverables: ['User API', 'Validation schemas', 'Error handling']
      }
    ],
    technologies: generateTechnologyStack(context)
  };
}

function generateAPIImplementationPlan(context: any): any {
  return {
    phases: [
      {
        name: 'API Design',
        tasks: ['Define API contract', 'Create request/response schemas', 'Plan error handling'],
        deliverables: ['API specification', 'Schemas', 'Error codes']
      },
      {
        name: 'Implementation',
        tasks: ['Implement route handlers', 'Add validation', 'Create tests'],
        deliverables: ['Route handlers', 'Validation', 'Test suite']
      }
    ],
    technologies: generateTechnologyStack(context)
  };
}

function generateGenericImplementationPlan(context: any): any {
  return {
    phases: [
      {
        name: 'Planning',
        tasks: ['Analyze requirements', 'Design API contract', 'Plan implementation'],
        deliverables: ['Requirements doc', 'API design', 'Implementation plan']
      },
      {
        name: 'Development',
        tasks: ['Implement core functionality', 'Add validation and error handling', 'Create tests'],
        deliverables: ['Core implementation', 'Validation layer', 'Test suite']
      }
    ],
    technologies: generateTechnologyStack(context)
  };
}

/**
 * Generate test plan
 */
function generateGenericTestPlan(endpoint: string, summary: string): any {
  return {
    unitTests: [
      'Request validation',
      'Business logic',
      'Error handling',
      'Response formatting'
    ],
    integrationTests: [
      'End-to-end API flow',
      'Database integration',
      'Authentication flow',
      'Error scenarios'
    ],
    testScenarios: [
      {
        scenario: 'Successful operation',
        given: 'Valid input data',
        when: 'API request is made',
        then: 'Expected response is returned'
      },
      {
        scenario: 'Invalid input',
        given: 'Invalid input data',
        when: 'API request is made',
        then: '400 Bad Request is returned'
      },
      {
        scenario: 'Unauthorized access',
        given: 'No or invalid authentication',
        when: 'API request is made',
        then: '401 Unauthorized is returned'
      }
    ]
  };
}

/**
 * Extract features from the summary text
 * This function attempts to identify key features mentioned in the summary
 * and generates structured metadata for each identified feature
 */
function extractFeaturesFromSummary(summary: string): any[] {
  // Convert summary to lowercase and split by common separators
  const words = summary.toLowerCase().split(/[,.:;]|\sand\s|\swith\s/);
  
  // Define feature patterns to look for
  const featurePatterns = [
    { 
      pattern: /multi-task|multiple tasks|task management/, 
      name: 'multi-task-specs',
      description: 'Support for defining complex tasks with multiple subtasks and dependencies',
      template: {
        structure: {
          tasks: 'Array of task objects that can be executed in sequence or parallel',
          dependencies: 'Graph representation of inter-task dependencies',
          globalParams: 'Parameters shared across all tasks in the spec'
        }
      }
    },
    { 
      pattern: /metadata|task metadata|data fields/, 
      name: 'task-metadata',
      description: 'Extended metadata for task tracking, visualization, and management',
      template: {
        fields: {
          owner: 'Person responsible for the task',
          priority: 'Task importance (low, medium, high, critical)',
          status: 'Current execution state'
        }
      }
    },
    { 
      pattern: /refine[_ -]spec|spec refinement|update specs/, 
      name: 'refine-spec-tool',
      description: 'Tool for iteratively refining and updating task specifications',
      template: {
        operations: {
          add: 'Add new tasks to existing specs',
          update: 'Modify existing task definitions',
          remove: 'Remove tasks from specs'
        }
      }
    },
    { 
      pattern: /notification|alerts|user notice/, 
      name: 'user-notifications',
      description: 'System for notifying users about task status changes and events',
      template: {
        channels: {
          inApp: 'Notifications within the Carrot UI',
          email: 'Email notifications for important events'
        }
      }
    },
    { 
      pattern: /documentation|docs|guides/, 
      name: 'documentation',
      description: 'Comprehensive documentation for Carrot features and APIs',
      template: {
        components: {
          userGuide: 'End-user documentation for Carrot',
          developerDocs: 'API documentation for developers'
        }
      }
    }
  ];
  
  // Identify features mentioned in the summary
  const identifiedFeatures = [];
  
  for (const { pattern, name, description, template } of featurePatterns) {
    if (words.some(word => pattern.test(word))) {
      identifiedFeatures.push({
        name,
        description,
        details: template
      });
    }
  }
  
  return identifiedFeatures;
}

/**
 * Determine the appropriate spec directory based on the endpoint
 */
function determineSpecDirectory(repoRoot: string, endpoint: string): string {
  // Analyze endpoint to determine appropriate subdirectory
  const lowerEndpoint = endpoint.toLowerCase();
  
  // API endpoints (most common case)
  if (lowerEndpoint.includes('/api/') || lowerEndpoint.startsWith('/api') || 
      lowerEndpoint.includes('endpoint') || lowerEndpoint.includes('route')) {
    return path.join(repoRoot, 'specs', 'api');
  }
  
  // UI/Component endpoints
  if (lowerEndpoint.includes('/ui/') || lowerEndpoint.includes('/component') || 
      lowerEndpoint.includes('/page') || lowerEndpoint.includes('/view')) {
    return path.join(repoRoot, 'specs', 'ui');
  }
  
  // Database/Schema endpoints
  if (lowerEndpoint.includes('/db/') || lowerEndpoint.includes('/database') || 
      lowerEndpoint.includes('/schema') || lowerEndpoint.includes('/model')) {
    return path.join(repoRoot, 'specs', 'db');
  }
  
  // Background job endpoints
  if (lowerEndpoint.includes('/job') || lowerEndpoint.includes('/task') || 
      lowerEndpoint.includes('/worker') || lowerEndpoint.includes('/queue')) {
    return path.join(repoRoot, 'specs', 'job');
  }
  
  // Default to api for any unrecognized patterns
  return path.join(repoRoot, 'specs', 'api');
} 