import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { z } from 'zod';
import * as fs from 'fs';
import * as path from 'path';
import * as yaml from 'js-yaml';

/**
 * Configure setup_carrot tool for initializing Carrot project structure
 */
export function setupCarrotTool(server: McpServer, repoRoot: string): void {
  server.tool(
    'setup_carrot',
    {
      projectName: z.string().optional().describe('Name of the project (defaults to directory name)'),
      description: z.string().optional().describe('Description of the project')
    },
    async ({ projectName, description }: { projectName?: string; description?: string }) => {
      try {
        console.log(`Setting up Carrot structure in: ${repoRoot}`);
        
        // Get project name from directory if not provided
        const defaultProjectName = path.basename(repoRoot);
        const finalProjectName = projectName || defaultProjectName;
        
        // Create directory structure
        const carrotDir = path.join(repoRoot, 'carrot');
        const specsDir = path.join(repoRoot, 'specs');
        const vibeYamlPath = path.join(repoRoot, 'vibe.yaml');
        
        // Create carrot directory
        if (!fs.existsSync(carrotDir)) {
          fs.mkdirSync(carrotDir, { recursive: true });
          console.log(`Created carrot directory: ${carrotDir}`);
        }
        
        // Create specs directory
        if (!fs.existsSync(specsDir)) {
          fs.mkdirSync(specsDir, { recursive: true });
          console.log(`Created specs directory: ${specsDir}`);
        }
        
        // Create subdirectories in specs
        const specSubDirs = ['api', 'ui', 'db', 'job'];
        for (const subDir of specSubDirs) {
          const subDirPath = path.join(specsDir, subDir);
          if (!fs.existsSync(subDirPath)) {
            fs.mkdirSync(subDirPath, { recursive: true });
            console.log(`Created specs/${subDir} directory`);
          }
        }
        
        // Create vibe.yaml if it doesn't exist
        if (!fs.existsSync(vibeYamlPath)) {
          const initialSpec = {
            openapi: '3.0.0',
            info: {
              title: `${finalProjectName} API`,
              version: '1.0.0',
              description: description || `API specification for ${finalProjectName} generated by Carrot MCP`
            },
            servers: [
              {
                url: 'http://localhost:8000',
                description: 'Development server'
              }
            ],
            paths: {},
            components: {
              schemas: {},
              responses: {
                'NotFound': {
                  description: 'The requested resource was not found',
                  content: {
                    'application/json': {
                      schema: {
                        type: 'object',
                        properties: {
                          error: { type: 'string', example: 'Resource not found' },
                          status: { type: 'integer', example: 404 }
                        }
                      }
                    }
                  }
                },
                'BadRequest': {
                  description: 'The request was invalid',
                  content: {
                    'application/json': {
                      schema: {
                        type: 'object',
                        properties: {
                          error: { type: 'string', example: 'Invalid request' },
                          status: { type: 'integer', example: 400 },
                          details: {
                            type: 'object',
                            additionalProperties: true
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          };
          
          fs.writeFileSync(vibeYamlPath, yaml.dump(initialSpec), { mode: 0o644 });
          console.log(`Created vibe.yaml: ${vibeYamlPath}`);
        }
        
        // Create initial FastAPI app structure in carrot directory
        const mainPyPath = path.join(carrotDir, 'main.py');
        if (!fs.existsSync(mainPyPath)) {
          const mainPyContent = `from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

app = FastAPI(
    title="${finalProjectName} API",
    description="${description || `API for ${finalProjectName}`}",
    version="1.0.0"
)

# Configure CORS
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # Configure appropriately for production
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

@app.get("/")
async def root():
    """Root endpoint"""
    return {"message": "Welcome to ${finalProjectName} API"}

@app.get("/health")
async def health_check():
    """Health check endpoint"""
    return {"status": "healthy"}

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)
`;
          
          fs.writeFileSync(mainPyPath, mainPyContent, { mode: 0o644 });
          console.log(`Created main.py: ${mainPyPath}`);
        }
        
        // Create __init__.py in carrot directory
        const initPyPath = path.join(carrotDir, '__init__.py');
        if (!fs.existsSync(initPyPath)) {
          fs.writeFileSync(initPyPath, '# Carrot API package\n', { mode: 0o644 });
          console.log(`Created __init__.py: ${initPyPath}`);
        }
        
        // Create requirements.txt if it doesn't exist
        const requirementsPath = path.join(repoRoot, 'requirements.txt');
        if (!fs.existsSync(requirementsPath)) {
          const requirements = `fastapi>=0.104.0
uvicorn[standard]>=0.24.0
pydantic>=2.0.0
python-multipart>=0.0.6
`;
          fs.writeFileSync(requirementsPath, requirements, { mode: 0o644 });
          console.log(`Created requirements.txt: ${requirementsPath}`);
        }
        
        // Create .gitignore if it doesn't exist
        const gitignorePath = path.join(repoRoot, '.gitignore');
        if (!fs.existsSync(gitignorePath)) {
          const gitignoreContent = `# Python
__pycache__/
*.py[cod]
*$py.class
*.so
.Python
build/
develop-eggs/
dist/
downloads/
eggs/
.eggs/
lib/
lib64/
parts/
sdist/
var/
wheels/
*.egg-info/
.installed.cfg
*.egg
MANIFEST

# Virtual environments
venv/
env/
ENV/

# IDE
.vscode/
.idea/
*.swp
*.swo

# OS
.DS_Store
Thumbs.db

# Logs
*.log
logs/

# Environment variables
.env
.env.local
.env.*.local
`;
          fs.writeFileSync(gitignorePath, gitignoreContent, { mode: 0o644 });
          console.log(`Created .gitignore: ${gitignorePath}`);
        }
        
        const createdItems = [];
        if (fs.existsSync(carrotDir)) createdItems.push('carrot/ directory');
        if (fs.existsSync(specsDir)) createdItems.push('specs/ directory with subdirectories');
        if (fs.existsSync(vibeYamlPath)) createdItems.push('vibe.yaml OpenAPI specification');
        if (fs.existsSync(mainPyPath)) createdItems.push('carrot/main.py FastAPI application');
        if (fs.existsSync(requirementsPath)) createdItems.push('requirements.txt');
        if (fs.existsSync(gitignorePath)) createdItems.push('.gitignore');
        
        return {
          content: [
            { 
              type: 'text', 
              text: `Successfully set up Carrot project structure in ${repoRoot}\n\n` +
                    `Created:\n${createdItems.map(item => `- ${item}`).join('\n')}\n\n` +
                    `Your project is now ready for Carrot development!\n\n` +
                    `Next steps:\n` +
                    `1. Install dependencies: pip install -r requirements.txt\n` +
                    `2. Run the API: python carrot/main.py\n` +
                    `3. Use other Carrot tools like add_route and grow_spec to build your API`
            }
          ]
        };
      } catch (error) {
        console.error(`Error in setup_carrot tool: ${error}`);
        return {
          content: [
            { 
              type: 'text', 
              text: `Error setting up Carrot structure: ${error instanceof Error ? error.message : String(error)}` 
            }
          ],
          isError: true
        };
      }
    }
  );
} 